### ISSUE TITLE
Css o bootstrap 

### ISSUE THREAD

**Issue by Miguel-Guerrero13** [Vinaza-24/Despl--Grupo1A-2020#10]
Que preferís hacer la página en css o bootstrap?

**Comment by Vinaza-24** [comment]
Para hacer la página yo veo mejor Bootstrap, ya que lo tenemos mas recientes y controlamos.

**Comment by jcrufra875** [comment]
Estaría bien empezarla en Bootstrap y si necesitamos maquetar algo, hacerlo con CSS
