### ISSUE TITLE
¿De que vamos hacer la Página?

### ISSUE THREAD

**Issue by Vinaza-24** [Vinaza-24/Despl--Grupo1A-2020#11]
Yo había pensado de hacer una pagina con temática de la NBA

**Comment by Miguel-Guerrero13** [comment]
Podemos hacer la página de una tienda de cachimbas.

**Comment by jcrufra875** [comment]
La opción de cachimbas me parece mejor , porque todos sabemos, porque por ejemplo, yo de la NBA, no entiendo ... 😅
